"""Recreate failed_login_attempts table

Revision ID: 0d51d4640b9e
Revises: e4c2a5e22bd8
Create Date: 2026-04-10 16:53:46.315256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d51d4640b9e'
down_revision: Union[str, Sequence[str], None] = 'e4c2a5e22bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deleted_accounts_id'), table_name='deleted_accounts')
    op.drop_index(op.f('ix_deleted_accounts_user_id'), table_name='deleted_accounts')
    op.drop_table('deleted_accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('deleted_accounts_pkey'))
    )
    op.create_index(op.f('ix_deleted_accounts_user_id'), 'deleted_accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_deleted_accounts_id'), 'deleted_accounts', ['id'], unique=False)
    # ### end Alembic commands ###
