"""add connections table

Revision ID: 58d0f1798275
Revises: 
Create Date: 2026-04-05 19:09:23.586050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58d0f1798275'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The ENUM type 'connectionstatus' may already exist, so we avoid recreating it if present.
    # If you need to recreate the type, drop it manually first or handle with checkfirst=True logic.
    op.create_table('connections',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('status', sa.Enum('pending', 'accepted', 'removed', name='connectionstatus'), server_default=sa.text("'pending'::connectionstatus"), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('connections_receiver_id_fkey')),
        sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('connections_sender_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('connections_pkey'))
    )
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('messages', sa.Column('ciphertexts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # op.drop_constraint(None, 'messages', type_='foreignkey')  # Removed: unnamed constraint
    # op.create_foreign_key(op.f('messages_group_id_fkey'), 'messages', 'groups', ['group_id'], ['id'], ondelete='CASCADE')  # Skipped to avoid duplicate constraint error
    # op.drop_index(op.f('ix_groups_id'), table_name='groups')
    # op.drop_constraint(None, 'group_members', type_='foreignkey')  # Removed: unnamed constraint
    # op.drop_constraint(None, 'group_members', type_='foreignkey')  # Removed: unnamed constraint
    # op.create_foreign_key(op.f('group_members_group_id_fkey'), 'group_members', 'groups', ['group_id'], ['id'], ondelete='CASCADE')  # Skipped to avoid duplicate constraint error
    # op.create_foreign_key(op.f('group_members_user_id_fkey'), 'group_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')  # Skipped to avoid duplicate constraint error
    # op.drop_index(op.f('ix_group_members_id'), table_name='group_members')
    # op.create_table('deleted_accounts',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    # sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name=op.f('deleted_accounts_pkey'))
    # )
    # op.create_index(op.f('ix_deleted_accounts_user_id'), 'deleted_accounts', ['user_id'], unique=False)  # Skipped to avoid duplicate index error
    # op.create_index(op.f('ix_deleted_accounts_id'), 'deleted_accounts', ['id'], unique=False)
    # op.create_table('profile_view_logs',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('viewer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('viewed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('profile_view_logs_profile_id_fkey')),
    # sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], name=op.f('profile_view_logs_viewer_id_fkey')),
    # sa.PrimaryKeyConstraint('id', name=op.f('profile_view_logs_pkey'))
    # )
    # op.create_index(op.f('ix_profile_view_logs_viewed_at'), 'profile_view_logs', ['viewed_at'], unique=False)
    # op.create_index(op.f('ix_profile_view_logs_id'), 'profile_view_logs', ['id'], unique=False)
    # ### end Alembic commands ###
