"""add resume_id to job_applications

Revision ID: bc596be350b8
Revises: 28d1f265c55d
Create Date: 2026-04-07 00:19:23.399728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc596be350b8'
down_revision: Union[str, Sequence[str], None] = '28d1f265c55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_view_logs_id'), table_name='profile_view_logs')
    op.drop_index(op.f('ix_profile_view_logs_viewed_at'), table_name='profile_view_logs')
    op.drop_table('profile_view_logs')
    op.drop_index(op.f('ix_deleted_accounts_id'), table_name='deleted_accounts')
    op.drop_index(op.f('ix_deleted_accounts_user_id'), table_name='deleted_accounts')
    op.drop_table('deleted_accounts')
    op.alter_column('connections', 'status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'removed', name='connectionstatus'),
               nullable=True,
               existing_server_default=sa.text("'pending'::connectionstatus"))
    op.create_index(op.f('ix_group_members_id'), 'group_members', ['id'], unique=False)
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.add_column('job_applications', sa.Column('resume_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_applications', 'resumes', ['resume_id'], ['id'])
    op.drop_column('messages', 'ciphertexts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('ciphertexts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.drop_column('job_applications', 'resume_id')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_index(op.f('ix_group_members_id'), table_name='group_members')
    op.alter_column('connections', 'status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'removed', name='connectionstatus'),
               nullable=False,
               existing_server_default=sa.text("'pending'::connectionstatus"))
    op.create_table('deleted_accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('deleted_accounts_pkey'))
    )
    op.create_index(op.f('ix_deleted_accounts_user_id'), 'deleted_accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_deleted_accounts_id'), 'deleted_accounts', ['id'], unique=False)
    op.create_table('profile_view_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('viewer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('viewed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('profile_view_logs_profile_id_fkey')),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], name=op.f('profile_view_logs_viewer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_view_logs_pkey'))
    )
    op.create_index(op.f('ix_profile_view_logs_viewed_at'), 'profile_view_logs', ['viewed_at'], unique=False)
    op.create_index(op.f('ix_profile_view_logs_id'), 'profile_view_logs', ['id'], unique=False)
    # ### end Alembic commands ###
