"""Add suggested_job_ids to Resume

Revision ID: e4c2a5e22bd8
Revises: 20260409_make_password_nullable
Create Date: 2026-04-10 16:48:09.187015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4c2a5e22bd8'
down_revision: Union[str, Sequence[str], None] = '20260409_make_password_nullable'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blockchain_logs_index'), table_name='blockchain_logs')
    op.drop_table('blockchain_logs')
    op.drop_index(op.f('ix_failed_login_attempts_email'), table_name='failed_login_attempts')
    op.drop_table('failed_login_attempts')
    op.drop_index(op.f('ix_deleted_accounts_id'), table_name='deleted_accounts')
    op.drop_index(op.f('ix_deleted_accounts_user_id'), table_name='deleted_accounts')
    op.drop_table('deleted_accounts')
    op.drop_column('profiles', 'skills')
    op.add_column('resumes', sa.Column('suggested_job_ids', sa.Text(), nullable=True))
    op.drop_column('users', 'must_reset_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_reset_password', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('resumes', 'suggested_job_ids')
    op.add_column('profiles', sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('deleted_accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('deleted_accounts_pkey'))
    )
    op.create_index(op.f('ix_deleted_accounts_user_id'), 'deleted_accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_deleted_accounts_id'), 'deleted_accounts', ['id'], unique=False)
    op.create_table('failed_login_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_attempt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('locked_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('failed_login_attempts_pkey'))
    )
    op.create_index(op.f('ix_failed_login_attempts_email'), 'failed_login_attempts', ['email'], unique=False)
    op.create_table('blockchain_logs',
    sa.Column('index', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('previous_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('block_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('index', name=op.f('blockchain_logs_pkey'))
    )
    op.create_index(op.f('ix_blockchain_logs_index'), 'blockchain_logs', ['index'], unique=False)
    # ### end Alembic commands ###
